Also add check-allow-merge action

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -9,6 +9,20 @@ on:
       - master
 
 jobs:
+  check-allow-merge:
+    runs-on: ubuntu-latest
+    steps:
+      # Labels in the context don't get updated so they are stuck at what's set during creation
+      # We need this action to get current labels
+      - name: Get current labels
+        uses: snnaplab/get-labels-action@v1
+      - name: Check if merge is allowed
+        if: github.base_ref == 'master' && github.head_ref != 'develop'
+        run: |
+          ${{ contains(fromJSON(env.LABELS), 'hotfix') }} && exit 0
+          echo "ERROR: You can only merge to master from develop or hotfixes."
+          exit 1
+
   check-labels:
     # Act doesn't set a pull request number by default, so we skip if it's 0
     if: github.event.pull_request.number != 0
